from __future__ import annotations


TEST_CATALOG: list[dict] = [
    # Motion / Kinematics
    {"id": "joint_sweep", "name": "Joint Sweep Test", "category": "Motion / Kinematics", "description": "Sweep joints through limits and detect collisions.", "supported_project_types": ["robot_dog", "robot_arm", "mechanism", "imported_cad_assembly", "generic"], "required_manifest_fields": ["joints"], "required_genesis_features": ["articulated_joints", "contact_collision"], "run_endpoint": "/projects/{project_id}/tests/joint_sweep/run", "parameters": {"sweep_samples": 24}, "output_metrics": ["collision_count", "joint_position_ranges"], "artifact_outputs": ["state_timeseries.json"], "implemented": True, "scenario_id": "joint_sweep_collision"},
    {"id": "mechanism_motion", "name": "Mechanism Motion Test", "category": "Motion / Kinematics", "description": "Runs a command sequence and validates achieved motion.", "supported_project_types": ["robot_dog", "robot_arm", "mechanism", "wheeled_rover", "imported_cad_assembly", "generic"], "required_manifest_fields": ["joints"], "required_genesis_features": ["articulated_joints"], "run_endpoint": "/projects/{project_id}/tests/mechanism_motion/run", "parameters": {"sequence": "default"}, "output_metrics": ["joint_position_ranges", "forward_distance_m"], "artifact_outputs": ["state_timeseries.json"], "implemented": True, "scenario_id": "walk_forward"},
    {"id": "end_effector_pose", "name": "End Effector Pose Test", "category": "Motion / Kinematics", "description": "Checks target pose reachability for manipulator.", "supported_project_types": ["robot_arm", "gripper"], "required_manifest_fields": ["joints", "actuators"], "required_genesis_features": ["articulated_joints"], "run_endpoint": "/projects/{project_id}/tests/end_effector_pose/run", "parameters": {"target_pose": [0.4, 0.0, 0.3]}, "output_metrics": ["pose_error"], "artifact_outputs": ["state_timeseries.json"], "implemented": False},
    {"id": "gait_motion", "name": "Gait Motion Test", "category": "Motion / Kinematics", "description": "Runs gait movement for legged robot.", "supported_project_types": ["robot_dog"], "required_manifest_fields": ["joints", "actuators"], "required_genesis_features": ["articulated_joints"], "run_endpoint": "/projects/{project_id}/tests/gait_motion/run", "parameters": {"gait": "walk"}, "output_metrics": ["forward_distance_m", "foot_contact_ratio"], "artifact_outputs": ["state_timeseries.json"], "implemented": True, "scenario_id": "walk_forward"},
    # Dynamics / Balance / Torque
    {"id": "stand_balance", "name": "Stand Balance", "category": "Dynamics / Balance / Torque", "description": "Stability at standstill.", "supported_project_types": ["robot_dog", "robot_arm", "gripper", "wheeled_rover", "imported_cad_assembly", "generic"], "required_manifest_fields": ["links"], "required_genesis_features": ["rigid_body_dynamics"], "run_endpoint": "/projects/{project_id}/tests/stand_balance/run", "parameters": {}, "output_metrics": ["max_pitch_deg", "max_roll_deg", "fall_detected"], "artifact_outputs": ["result.json"], "implemented": True, "scenario_id": "stand_balance"},
    {"id": "torque_margin", "name": "Torque Margin", "category": "Dynamics / Balance / Torque", "description": "Checks actuator torque headroom.", "supported_project_types": ["robot_dog", "robot_arm", "mechanism", "gripper"], "required_manifest_fields": ["actuators"], "required_genesis_features": ["articulated_joints"], "run_endpoint": "/projects/{project_id}/tests/torque_margin/run", "parameters": {"required_safety_factor": 1.2}, "output_metrics": ["min_torque_margin"], "artifact_outputs": ["metrics.json"], "implemented": True, "scenario_id": "torque_margin"},
    {"id": "payload_carry", "name": "Payload Carry", "category": "Dynamics / Balance / Torque", "description": "Evaluates stability with payload.", "supported_project_types": ["robot_dog", "robot_arm", "wheeled_rover"], "required_manifest_fields": ["payloads"], "required_genesis_features": ["rigid_body_dynamics"], "run_endpoint": "/projects/{project_id}/tests/payload_carry/run", "parameters": {"payload_kg": 5.0}, "output_metrics": ["fall_detected", "min_torque_margin"], "artifact_outputs": ["result.json"], "implemented": True, "scenario_id": "payload_carry"},
    {"id": "tip_over", "name": "Tip-Over Test", "category": "Dynamics / Balance / Torque", "description": "Evaluates toppling under perturbation.", "supported_project_types": ["robot_dog", "wheeled_rover"], "required_manifest_fields": ["links", "joints"], "required_genesis_features": ["contact_collision"], "run_endpoint": "/projects/{project_id}/tests/tip_over/run", "parameters": {}, "output_metrics": ["fall_detected"], "artifact_outputs": ["result.json"], "implemented": False},
    # Contact / Collision
    {"id": "collision_check", "name": "Collision Check", "category": "Contact / Collision", "description": "Runs collision and contact checks.", "supported_project_types": ["robot_dog", "robot_arm", "mechanism", "imported_cad_assembly", "generic"], "required_manifest_fields": ["collision_primitives"], "required_genesis_features": ["contact_collision"], "run_endpoint": "/projects/{project_id}/tests/collision_check/run", "parameters": {}, "output_metrics": ["collision_count", "foot_contact_ratio"], "artifact_outputs": ["state_timeseries.json"], "implemented": True, "scenario_id": "joint_sweep_collision"},
    {"id": "component_fit", "name": "Component Interference Test", "category": "Contact / Collision", "description": "Checks internal packaging collisions.", "supported_project_types": ["robot_dog", "robot_arm", "mechanism", "imported_cad_assembly"], "required_manifest_fields": ["links", "collision_primitives"], "required_genesis_features": ["contact_collision"], "run_endpoint": "/projects/{project_id}/tests/component_fit/run", "parameters": {}, "output_metrics": ["collision_count"], "artifact_outputs": ["result.json"], "implemented": True, "scenario_id": "component_fit"},
    # Terrain / Environment
    {"id": "terrain_slope", "name": "Slope Terrain Test", "category": "Terrain / Environment", "description": "Tests movement on slope.", "supported_project_types": ["robot_dog", "wheeled_rover"], "required_manifest_fields": ["environments"], "required_genesis_features": ["terrain_simulation"], "run_endpoint": "/projects/{project_id}/tests/terrain_slope/run", "parameters": {"slope_deg": 12.0}, "output_metrics": ["forward_distance_m", "fall_detected"], "artifact_outputs": ["result.json"], "implemented": True, "scenario_id": "slope_climb"},
    {"id": "terrain_rough", "name": "Rough Terrain Test", "category": "Terrain / Environment", "description": "Tests stability on rough terrain.", "supported_project_types": ["robot_dog", "wheeled_rover"], "required_manifest_fields": ["environments"], "required_genesis_features": ["terrain_simulation"], "run_endpoint": "/projects/{project_id}/tests/terrain_rough/run", "parameters": {}, "output_metrics": ["forward_distance_m", "fall_detected"], "artifact_outputs": ["result.json"], "implemented": True, "scenario_id": "rough_terrain"},
    # Sensors / Perception
    {"id": "sensor_visibility", "name": "Sensor Visibility Test", "category": "Sensors / Perception", "description": "Checks front sensor clearance.", "supported_project_types": ["robot_dog", "robot_arm", "wheeled_rover", "generic"], "required_manifest_fields": ["sensors"], "required_genesis_features": ["sensor_simulation"], "run_endpoint": "/projects/{project_id}/tests/sensor_visibility/run", "parameters": {}, "output_metrics": ["sensor_clearance"], "artifact_outputs": ["result.json"], "implemented": True, "scenario_id": "sensor_visibility"},
    {"id": "imu_output", "name": "IMU Stability Test", "category": "Sensors / Perception", "description": "Evaluates orientation/tilt from simulated data.", "supported_project_types": ["robot_dog", "robot_arm", "wheeled_rover", "drone", "generic"], "required_manifest_fields": ["sensors"], "required_genesis_features": ["sensor_simulation"], "run_endpoint": "/projects/{project_id}/tests/imu_output/run", "parameters": {}, "output_metrics": ["max_pitch_deg", "max_roll_deg"], "artifact_outputs": ["sensor_output.json"], "implemented": True, "scenario_id": "stand_balance"},
    # Rendering / Camera Output
    {"id": "camera_render", "name": "Camera Render Test", "category": "Rendering / Camera Output", "description": "Produces camera/render artifacts.", "supported_project_types": ["robot_dog", "robot_arm", "wheeled_rover", "generic"], "required_manifest_fields": ["render_cameras"], "required_genesis_features": ["camera_sensor_rendering"], "run_endpoint": "/projects/{project_id}/tests/camera_render/run", "parameters": {}, "output_metrics": ["render_frames"], "artifact_outputs": ["render_output.json"], "implemented": False},
    # Materials / Mass / Friction
    {"id": "material_mass_friction", "name": "Material/Mass/Friction Test", "category": "Materials / Mass / Friction", "description": "Evaluates friction, mass and slip sensitivity.", "supported_project_types": ["robot_dog", "robot_arm", "wheeled_rover", "mechanism", "generic"], "required_manifest_fields": ["materials", "links"], "required_genesis_features": ["rigid_body_dynamics"], "run_endpoint": "/projects/{project_id}/tests/material_mass_friction/run", "parameters": {"surface": "default"}, "output_metrics": ["fall_detected", "forward_distance_m"], "artifact_outputs": ["metrics.json"], "implemented": True, "scenario_id": "stand_balance"},
    # Soft / Wires / Cables
    {"id": "wire_route", "name": "Wire Route Sanity", "category": "Soft / Wires / Cables", "description": "Checks cable route bend and interference.", "supported_project_types": ["robot_dog", "robot_arm", "mechanism", "imported_cad_assembly", "generic"], "required_manifest_fields": ["wires"], "required_genesis_features": ["wire_route_approximation"], "run_endpoint": "/projects/{project_id}/tests/wire_route/run", "parameters": {}, "output_metrics": ["collision_count"], "artifact_outputs": ["result.json"], "implemented": True, "scenario_id": "wire_route"},
    # Payload / Load Handling
    {"id": "payload_shift", "name": "Payload Shift Test", "category": "Payload / Load Handling", "description": "Checks stability with off-center payload.", "supported_project_types": ["robot_dog", "robot_arm", "wheeled_rover"], "required_manifest_fields": ["payloads"], "required_genesis_features": ["rigid_body_dynamics"], "run_endpoint": "/projects/{project_id}/tests/payload_shift/run", "parameters": {"payload_kg": 5.0}, "output_metrics": ["fall_detected", "min_torque_margin"], "artifact_outputs": ["result.json"], "implemented": False},
    # Control / Firmware-in-the-loop
    {"id": "control_script", "name": "Control Script Test", "category": "Control / Firmware-in-the-loop", "description": "Runs configured control script interface.", "supported_project_types": ["robot_dog", "robot_arm", "wheeled_rover", "gripper", "mechanism", "generic"], "required_manifest_fields": ["controls"], "required_genesis_features": ["controllers"], "run_endpoint": "/projects/{project_id}/tests/control_script/run", "parameters": {"script": "default"}, "output_metrics": ["step_count", "status"], "artifact_outputs": ["logs.txt"], "implemented": False},
    # Imported CAD Validation
    {"id": "imported_cad_validation", "name": "Imported STEP Collision Test", "category": "Imported CAD Validation", "description": "Validates imported STEP/URDF/MJCF metadata and collisions.", "supported_project_types": ["imported_cad_assembly", "generic", "robot_arm", "robot_dog", "mechanism"], "required_manifest_fields": ["assets", "collision_primitives"], "required_genesis_features": ["contact_collision"], "run_endpoint": "/projects/{project_id}/tests/imported_cad_validation/run", "parameters": {}, "output_metrics": ["collision_count", "metadata_gaps"], "artifact_outputs": ["result.json"], "implemented": True, "scenario_id": "component_fit"},
    # Full Suite
    {"id": "full_project_suite", "name": "Full Project Test Suite", "category": "Full Project Test Suite", "description": "Runs all available tests for current project.", "supported_project_types": ["robot_dog", "robot_arm", "wheeled_rover", "gripper", "drone", "mechanism", "imported_cad_assembly", "generic"], "required_manifest_fields": [], "required_genesis_features": ["rigid_body_dynamics"], "run_endpoint": "/projects/{project_id}/tests/run-suite", "parameters": {}, "output_metrics": ["suite_pass_rate"], "artifact_outputs": ["suite_result.json"], "implemented": True},
]


def get_test_catalog() -> list[dict]:
    return TEST_CATALOG
